trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - .gitignore

variables:
  pythonVersion: '3.12'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
        addToPath: true
      displayName: 'Use Python $(pythonVersion)'

    # Install Chrome and set up environment for ChromeDriver
    - script: |
        # Install Chrome
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

        # Print Chrome version for logging
        google-chrome --version
        
        # Set up environment variables for webdriver-manager
        echo "##vso[task.setvariable variable=WDM_LOG_LEVEL]0"
        echo "##vso[task.setvariable variable=WDM_PROGRESS_BAR]0"
      displayName: 'Install Chrome'

    # Install Python dependencies
    - script: |
        python -m pip install --upgrade pip
        pip install gunicorn==21.2.0
        pip install -r requirements.txt
      displayName: 'Install Python dependencies'

    # Create startup script
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cat > startup.sh << 'EOF'
          #!/bin/bash
          set -e  # Exit on any error

          # Check if Chrome is installed
          if ! command -v google-chrome &> /dev/null; then
              echo "Installing Chrome..."
              curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
              echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
              apt-get update
              apt-get install -y google-chrome-stable
          fi

          # Set environment name based on app service name
          if [[ $WEBSITE_HOSTNAME == *"-test"* ]]; then
              cp .env.test .env
          else
              cp .env.prod .env
          fi

          # Start the application with gunicorn
          exec gunicorn --bind=0.0.0.0 --timeout 600 --workers 2 --threads 2 app:app
          EOF

          chmod +x startup.sh
      displayName: 'Create startup script'

    # Create test environment file
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cat > .env.test << EOF
          TWITTER_USERNAME=$(TWITTER_USERNAME)
          TWITTER_PASSWORD=$(TWITTER_PASSWORD)
          TWITTER_PHONE_NUMBER=$(TWITTER_PHONE_NUMBER)
          TWITTER_BASE_URL=https://x.com
          EOF
      displayName: 'Create test environment file'
      env:
        TWITTER_USERNAME: $(TWITTER_USERNAME)
        TWITTER_PASSWORD: $(TWITTER_PASSWORD)
        TWITTER_PHONE_NUMBER: $(TWITTER_PHONE_NUMBER)

    # Create prod environment file
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cat > .env.prod << EOF
          TWITTER_USERNAME=$(TWITTER_USERNAME)
          TWITTER_PASSWORD=$(TWITTER_PASSWORD)
          TWITTER_PHONE_NUMBER=$(TWITTER_PHONE_NUMBER)
          TWITTER_BASE_URL=https://x.com
          EOF
      displayName: 'Create prod environment file'
      env:
        TWITTER_USERNAME: $(TWITTER_USERNAME)
        TWITTER_PASSWORD: $(TWITTER_PASSWORD)
        TWITTER_PHONE_NUMBER: $(TWITTER_PHONE_NUMBER)

    # Archive files
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true
        verbose: true
      displayName: 'Archive project files'

    # Publish artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish artifacts'

- stage: DeployTest
  displayName: 'Deploy to Test'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployTest
    environment: 'test'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              appName: 'smd-pythonapi-test'
              package: '$(System.ArtifactsDirectory)/drop/app.zip'
              appType: 'webAppLinux'
              runtimeStack: 'PYTHON|3.12'
              startUpCommand: 'bash startup.sh'
              healthCheckPath: '/health'

- stage: DeployProd
  displayName: 'Deploy to Production'
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    environment: 'prod'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              appName: 'smd-pythonapi-prod'
              package: '$(System.ArtifactsDirectory)/drop/app.zip'
              appType: 'webAppLinux'
              runtimeStack: 'PYTHON|3.12'
              startUpCommand: 'bash startup.sh'
              healthCheckPath: '/health'